name: Tests

on:
  push:
    branches:
    - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # [macos-latest, windows-latest, ubuntu-latest]
        version: [0.4.2]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: ./
      with:
        cli: fetch
        #hub: "gitlab.com"
        repo: "gruntwork-io/fetch"
        version: ${{ matrix.version }}

    - name: Capture version installed
      run: |
        export CLI_VERSION=$( ${{steps.setup.outputs.cli}} --version )
        echo 'VERSION_INSTALLED<<EOF' >> $GITHUB_ENV
        ${{steps.setup.outputs.cli}} --version >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: Verify
      shell: python
      env:
        VERSION_EXPECTED: ${{ matrix.version }}
      run: |
        import sys, os
        sys.exit(
            int(not os.environ["VERSION_EXPECTED"] in os.environ["VERSION_INSTALLED"])
        )
